105 api exceptions
PhilippHerda/black-mirror-app pull request #28
Opened 2022-06-20 18:34 UTC by Luisg111

2022-06-21 06:35 UTC, nbinderHHN approved these changes
Sollte passen, bei dem Kommentar bin ich mir unsicher, ob das was bringt

2022-06-21 06:35 UTC, nbinderHHN commented on app/src/main/java/de/hhn/aib/labsw/blackmirror/controller/API/Websockets/MirrorApiWebsockets.kt
> +                delay(5 * 1000)
Timer funktioniert eventuell besser

2022-06-21 07:03 UTC, nbinderHHN commented on app/src/main/java/de/hhn/aib/labsw/blackmirror/controller/API/Websockets/ApiExceptionListener.kt
> +
documentation

2022-06-21 07:04 UTC, nbinderHHN requested changes, later dismissed

2022-06-21 07:04 UTC, nbinderHHN commented on app/src/main/java/de/hhn/aib/labsw/blackmirror/controller/API/Websockets/ApiException.kt
> +
documentation

2022-06-21 07:27 UTC, Code-Mozart requested changes
Change and fix problems as discussed

2022-06-26 21:40 UTC, Code-Mozart approved these changes

2022-06-27 09:38 UTC, PhilippHerda approved these changes

2022-06-27 09:39 UTC, merged